### ISSUE TITLE
Upgrade from 1.5 to 2.1 RC resulted in data loss

### ISSUE THREAD

**Issue by that-guy-iain** [plausible/community-edition#116]
Just a heads up but I just did the upgrade to the latest RC, turns out I was all the way back on v1.5 and following the upgrade steps all worked except for the analytics data being transferred over. Everything but the analytics is still there, users, sites, settings, etc. It's just my analytics that disappeared. 

For me, this isn't that big of a deal, but I am sure for others this is a massive issue.

**Comment by ruslandoga** [comment]
👋 @that-guy-iain 

Please see v2 upgrade guide to make analytics visible in the dashboards.

**Comment by that-guy-iain** [comment]
Ah, thanks!
