### ISSUE TITLE
URL not recognized correctly

### ISSUE THREAD

**Issue by webmastermario** [plausible/community-edition#177]
Hello,

i use the community edition with docker and i have on my live site URLs like http://example.com/file/?filename
http://example.com/file/?filename2 etc (with a questionmark). But on the dashboard it only shows as /file/ for all URLs.

Is there a way to show this correctly or does this not work in general?

Thanks

**Comment by ruslandoga** [comment]
👋 @webmastermario 

There might be something in https://plausible.io/docs

**Comment by ruslandoga** [comment]
I checked the ingestion code, and it seems like it's not possible right now.

- the request struct does read [query params](https://github.com/plausible/analytics/blob/0404522b5a85c51e81a653e5a8315cfefe22161c/lib/plausible/ingestion/request.ex#L248-L256)
- but the event only uses these `request.query_params` for [utm tags](https://github.com/plausible/analytics/blob/0404522b5a85c51e81a653e5a8315cfefe22161c/lib/plausible/ingestion/event.ex#L265-L275) and [referrers](https://github.com/plausible/analytics/blob/0404522b5a85c51e81a653e5a8315cfefe22161c/lib/plausible/ingestion/event.ex#L406-L417)

You might be able to use [props](https://plausible.io/docs/custom-props/introduction) or [custom events](https://plausible.io/docs/custom-event-goals) for these file downloads.
